// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class LoginTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void login() {
    // Test name: Login
    // Step # | name | target | value | comment
    // 1 | open | / |  | 
    driver.get("https://campus-connect-ecru.vercel.app/");
    // 2 | setWindowSize | 1268x652 |  | 
    driver.manage().window().setSize(new Dimension(1268, 652));
    // 3 | click | css=.MuiButton-outlined |  | 
    driver.findElement(By.cssSelector(".MuiButton-outlined")).click();
    // 4 | click | css=.MuiFormControl-root:nth-child(1) |  | 
    driver.findElement(By.cssSelector(".MuiFormControl-root:nth-child(1)")).click();
    // 5 | click | css=.MuiFormControl-root:nth-child(1) |  | 
    driver.findElement(By.cssSelector(".MuiFormControl-root:nth-child(1)")).click();
    // 6 | type | id=email | 202001011@daiict.ac.in | 
    driver.findElement(By.id("email")).sendKeys("202001011@daiict.ac.in");
    // 7 | click | id=password |  | 
    driver.findElement(By.id("password")).click();
    // 8 | mouseOver | css=.MuiButton-containedPrimary |  | 
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButton-containedPrimary"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 9 | type | id=password | 2345 | 
    driver.findElement(By.id("password")).sendKeys("2345");
    // 10 | click | css=.MuiButton-containedPrimary |  | 
    driver.findElement(By.cssSelector(".MuiButton-containedPrimary")).click();
    // 11 | mouseOut | css=.MuiButton-containedPrimary |  | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 12 | assertAlert | Invalid Username and Password, Please try again! |  | 
    assertThat(driver.switchTo().alert().getText(), is("Invalid Username and Password, Please try again!"));
    // 13 | click | id=password |  | 
    driver.findElement(By.id("password")).click();
    // 14 | click | css=.css-yvefuq |  | 
    driver.findElement(By.cssSelector(".css-yvefuq")).click();
    // 15 | mouseOver | css=.MuiButton-containedPrimary |  | 
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButton-containedPrimary"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 16 | type | id=password | Horse#07 | 
    driver.findElement(By.id("password")).sendKeys("Horse#07");
    // 17 | click | css=.MuiButton-containedPrimary |  | 
    driver.findElement(By.cssSelector(".MuiButton-containedPrimary")).click();
    // 18 | assertAlert | Logged in successfully |  | 
    assertThat(driver.switchTo().alert().getText(), is("Logged in successfully"));
  }
}
