const menu = [
    {
      id: 1,
      title: "Anil Roy",
      Qualifications: "Phd(Physics)",
      Phone: "079-68261613",
      location: "# 1104, FB-1, DA-IICT, Gandhinagar, Gujarat, India – 382007",
      email: "anil_roy@daiict.ac.in",
      img: "https://www.daiict.ac.in/sites/default/files/faculty_image/anil-roy-new.jpg",
      research: "Applications of Image Processing, Fiber Optics and Optical Communication, High speed Semiconductor Devices, Nanoscience and Nanotechnology, Quantum Optics, Technologies for Humanitarian Challenges",
    },
    {
      id: 2,
      title: "Pritam Anand",
      Qualifications: "Phd(Computer Science)",
      Phone: "079-68261657",
      location: "# 3103, FB-3, DA-IICT, Gandhinagar, Gujarat, India – 382007",
      email: "pritam_anand@daiict.ac.in",
      img: "https://www.daiict.ac.in/sites/default/files/faculty_image/Prof-Pritam-Anand.jpg",
      research: "Support Vector Machines, Loss Functions, Regression, Extreme Learning Machine, Quantile Regression",
    },
    {
      id: 3,
      title: "Jaideep Mulherkar",
      Qualifications: "Phd(Mathematics)",
      Phone: "079-68261595",
      location: "# 1204, FB-1, DA-IICT, Gandhinagar, Gujarat, India – 382007",
      email: "jaideep_mulherkar@daiict.ac.in",
      img: "https://www.daiict.ac.in/sites/default/files/faculty_image/Jaideep-Mulherkar.jpg",
      research: "Quantum Computation and Information, Quantum Spin Systems, Mathematical Finance",
    },
    {
      id: 4,
      title: "Yash Vasavada",
      Qualifications: "Phd(Electrical Engineering)",
      Phone: "079-68261634",
      location: "# 1224, FB-1, DA-IICT, Gandhinagar, Gujarat, India – 382007",
      email: "yash_vasavada@daiict.ac.in",
      img: "https://www.daiict.ac.in/sites/default/files/faculty_image/yash-vasavda.jpg",
      research: "Communication, Signal Processing, Machine Learning",
    },
    {
      id: 5,
      title: "Rahul Muthu",
      Qualifications: "Phd(Mathematics)",
      Phone: "079-68261564",
      location: "# 1202, FB-1, DA-IICT, Gandhinagar, Gujarat, India – 382007",
      email: "rahul_muthu@daiict.ac.in",
      img: "https://www.daiict.ac.in/sites/default/files/faculty_image/Rahul-Muthu.jpg",
      research: "Graph Theory, Data Structures, Algorithms, Automata Theory",
    },
  ];
export default menu;